package challenge_1.exceptions;

public class UserNotFoundException extends RuntimeException {

}
